Added RST IoC Lookup connector. Fixes for Report Hub and Threat Feed
OpenCTI-Platform/connectors pull request #2864
Opened 2024-10-29 02:43 UTC by k1r10n

### Proposed changes
* A new RST IoC Lookup Connector: cost-effective and functional enrichment connector for observables and indicators
* New parameters to give options for users to disable/enable generation of 'related-to' and observables when using the RST Report Hub connector
* Minor fixes to RST Threat Feed connector: indicator patterns standardised, only_new logic changed, code reformatting, description are nulled for high level objects as intrusion-set, malware, tools, etc profiles are to come from RST Threat Library

### Related issues
* Usage of 'related-to' relationships is not recommended https://github.com/OpenCTI-Platform/connectors/issues/2767
* It is recommended to clone indicators to observables at import time https://github.com/OpenCTI-Platform/connectors/issues/2767

### Checklist
- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality using different use cases
- [x] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### Further comments

2024-11-13 16:21 UTC, Powlinett reviewed
Hi @k1r10n , thank you for your PR and this new connector!

As I wrote in the comments, there is an issue with `CONNECTOR_UPDATE_EXISTING_DATA` env var:
- **rst-threat-hub** doesn't ingest anything as `VALIDATION_ERROR` is raised for each message
- **rst-threat-feed** ingests data and I didn't see any `VALIDATION_ERROR` so far (there are many `MISSING_REFERENCE_ERROR` but it's already the case on master, your fixes/updates are not responsible)
- I tested **rst-ioc-lookup** manually and in auto mode, it seems to working as intended in both ways

FIY, all my tests have been done by running connectors locally with env vars set in `config.yml`.

Could you fix the issue in the comments so we can merge your PR please? Thanks 😇

2024-11-13 16:21 UTC, Powlinett commented on external-import/rst-report-hub/src/main.py
> +            True,
I'm not sure it does what it's supposed to do. `True` here refers to `isNumber` argument (which parse an environment variable to an integer), but I think `self.update_existing_data` needs to be a boolean.
If not, a `VALIDATION_ERROR ` is raised during ingestion.

2024-11-13 16:21 UTC, Powlinett commented on external-import/rst-threat-feed/src/main.py
> +            True,
Same issue as in rst-report-hub connector

2024-11-14 14:19 UTC, k1r10n commented on external-import/rst-threat-feed/src/main.py
> +            True,
Is it because the variable CONNECTOR_UPDATE_EXISTING_DATA was deprecated? Should we remove it as now merging is done using confidence levels?

2024-11-22 23:42 UTC, k1r10n commented on external-import/rst-threat-feed/src/main.py
> +            True,
@Powlinett ok, just fixed that than

2024-12-02 06:03 UTC, k1r10n commented
Hi @Powlinett, this PR has been open for a while. Please take a look and merge it when you have time.

2025-01-05 05:54 UTC, k1r10n commented
Happy New Year! :)

2025-01-08 07:19 UTC, helene-nguyen submitted a review, later dismissed

2025-01-08 07:19 UTC, helene-nguyen commented
@k1r10n Happy new year to you too :)
Could you sign your commits to allow us to merge the PR ?

2025-01-08 09:47 UTC, helene-nguyen requested changes
Could you please sign your commits ?

2025-01-09 15:33 UTC, helene-nguyen commented
@k1r10n Thank you so much for your effort! All commits need to have verified signatures. Would you mind adding that when you get a chance? 😊

2025-01-14 10:32 UTC, helene-nguyen commented
@k1r10n Sorry again, all commits need to have verified signatures and some haven't. Would you mind adding that ?

2025-01-16 10:53 UTC, helene-nguyen approved these changes
Thanks for your contribution ! Everything looks great on our end :)

2025-01-16 11:24 UTC, merged