[WIZ] Init Connector
OpenCTI-Platform/connectors pull request #2893
Opened 2024-11-01 16:33 UTC by Renizmy

### Proposed changes

* Create Wiz external import connector

### Related issues

*   #https://github.com/OpenCTI-Platform/connectors/issues/2368

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality using different use cases
- [x] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

2024-11-15 08:18 UTC, helene-nguyen commented on external-import/wiz/entrypoint.sh
> +cd /opt/opencti-connector-template
Thanks for your contribution @Renizmy !

This won't work because in you Dockerfile, the connector have been properly renamed.

Please remove `Template` or `template` word and replace by your connector name as the following instructions: https://github.com/OpenCTI-Platform/connectors/tree/master/templates#changing-the-template

Thanks in advance

2024-11-15 08:18 UTC, helene-nguyen commented on external-import/wiz/README.md
> +# OpenCTI External Ingestion Connector Template
Could you complete the documentation to explain what the connector does ?

2024-11-17 14:20 UTC, Renizmy commented
Done,

I noticed an issue. In the UI, the number of operation inside a work is not correct:

![image](https://github.com/user-attachments/assets/94424628-4b33-4f56-b803-fb0f4a708f83)

Do you have an idea how I could fix it ?

2024-11-17 14:23 UTC, Renizmy commented on external-import/wiz/entrypoint.sh
> +cd /opt/opencti-connector-template
Done, How about a makefile to create the right file structure ? It would help avoid these problems

2024-11-20 08:05 UTC, helene-nguyen commented on external-import/wiz/entrypoint.sh
> +cd /opt/opencti-connector-template
@Renizmy Yes, a good point here to improve this :)

2024-11-20 08:07 UTC, helene-nguyen commented
@Renizmy yes, we can help. To better assist you, could you clarify what you’re expecting here?

> Done,
> 
> I noticed an issue. In the UI, the number of operation inside a work is not correct:
> 
> ![image](https://private-user-images.githubusercontent.com/62422302/386966372-94424628-4b33-4f56-b803-fb0f4a708f83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwOTAyMjksIm5iZiI6MTczMjA4OTkyOSwicGF0aCI6Ii82MjQyMjMwMi8zODY5NjYzNzItOTQ0MjQ2MjgtNGIzMy00ZjU2LWI4MDMtZmIwZjRhNzA4ZjgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDA4MDUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzZWUzNTg4NTZhNTQ1NDMyODIzYmM4NmE2OWJhNmVmZGIzMTNmMGQzZjRlMTY1OWE5ODViMWM0ODgwM2YxNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SCvALPEyiRtOOzmmMDAjRVpI7PkiTN0n9oGykCUhScs)
> 
> Do you have an idea how I could fix it ?

2024-11-20 08:33 UTC, Renizmy commented
@helene-nguyen, I am maybe wrong but I expect to see the number of bundles sent in this work context (run) ?

2024-11-22 05:56 UTC, helene-nguyen commented on external-import/wiz/src/external_import_connector/connector.py
> +                )
@Renizmy Ok, I see. You need to add the work ID that you have initiated before to allow OpenCTI to identify the job to be processed

```suggestion
                bundles_sent = self.helper.send_stix2_bundle(
                    stix_objects_bundle, 
                    work_id=work_id
                    update=True
                )
```

2025-01-08 07:15 UTC, helene-nguyen submitted a review, later dismissed

2025-01-09 09:52 UTC, helene-nguyen requested changes
All commits need to be signed and verified. Could you please check it to allow us to merge the PR ?

2025-01-09 21:52 UTC, Renizmy commented
@helene-nguyen done. I had forgotten one, sorry

2025-01-13 10:43 UTC, helene-nguyen approved these changes

2025-01-13 13:35 UTC, merged