[IPSum ] Add connector
OpenCTI-Platform/connectors pull request #3002
Opened 2024-11-20 17:48 UTC by baptiste-fourmont

### Proposed changes

* [Add] IPsum connector: https://github.com/stamparm/ipsum/tree/master
IPsum is a threat intelligence feed based on 30+ different publicly available [lists](https://github.com/stamparm/maltrail) of suspicious and/or malicious IP addresses. All lists are automatically retrieved and parsed on a daily (24h) basis and the final result is pushed to this repository. By default, I have choose the list "5" because it contains [ultra false positives](https://raw.githubusercontent.com/stamparm/ipsum/master/levels/5.txt)

I have used the new connector template to do this

### Related issues

* No one

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality using different use cases
- [X] I added/update the relevant documentation (either on github or on notion)
- [X] Where necessary I refactored code to improve the overall quality

### Further comments

2024-12-24 13:20 UTC, flavienSindou reviewed
Thank you for your contribution and the work you've put into this! I’ve reviewed the pull request, and here are a few suggestions for improvement to ensure the project remains consistent and clear:
* Update the README file with the correct variable names for better clarity.
* Remove any unnecessary comments from the code to keep it clean and focused.
* Add this project to CircleCI for continuous integration and deployment pipeline file.

Let me know if you need any assistance with these changes. Thanks again for your efforts!

2025-01-06 11:04 UTC, baptiste-fourmont commented
Hello Flavien,

I have made the modfication according to your feedback :)
@flavienSindou

2025-01-07 09:37 UTC, flavienSindou approved these changes
Thank you @baptiste-fourmont

2025-01-08 09:55 UTC, flavienSindou requested changes
Hello @baptiste-fourmont, I wasn’t able to merge your Pull Request quickly enough, and a merge conflict has appeared.

Could you please resolve it or add me as a project contributor so I can take care of it?

2025-01-08 11:23 UTC, baptiste-fourmont commented
Hello For personal reasons I can't do it this week. I added you as a contributor. Thank you

2025-01-13 08:54 UTC, flavienSindou commented
> I have made the changes @flavienSindou

Thank you very much, we are currently releasing a new OCTI version . Your contribution will be merged during the current day, right after our release process is over !

2025-01-13 13:35 UTC, flavienSindou approved these changes

2025-01-13 13:35 UTC, merged