[Hunt IO] Connector for importing C2 feed into OpenCTI
OpenCTI-Platform/connectors pull request #3033
Opened 2024-11-26 14:58 UTC by m4r35

### Proposed changes

*
*

### Related issues

*
*

### Checklist

- [ ] I consider the submitted work as finished
- [ ] I tested the code for its functionality using different use cases
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

2024-12-03 13:31 UTC, Jipegien commented
@helene-nguyen for your team to review

2025-01-09 10:06 UTC, helene-nguyen requested changes
@m4r35 Thanks for the contribution !
All commits need to be signed and verified, could you please sign your commits to allow us to merge the PR ?

2025-01-13 10:37 UTC, helene-nguyen commented on external-import/hunt-io/src/external_import_connector/config_variables.py
> +            ["connector_hunt-io", "api_base_url"],
@m4r35 Could you correct the configuration and replace"-" by "_"? Thank you :)

```suggestion
            ["connector_hunt_io", "api_base_url"],
```

2025-01-13 10:37 UTC, helene-nguyen commented on external-import/hunt-io/src/external_import_connector/config_variables.py
> +            ["connector_hunt-io", "api_key"],
Same here

```suggestion
            ["connector_hunt_io", "api_key"],
```

2025-01-16 09:43 UTC, m4r35 commented on external-import/hunt-io/src/external_import_connector/config_variables.py
> +            ["connector_hunt-io", "api_base_url"],
Fixed.

2025-01-16 10:29 UTC, helene-nguyen approved these changes
Everything looks great on our end, thanks again for the contribution !

2025-01-16 10:50 UTC, merged