Added Beautifulsoup parsing and cleaned up code
OpenCTI-Platform/connectors pull request #3047
Opened 2024-11-28 17:16 UTC by pietrocapece

### Proposed changes

* Added HTML parsing of the content of alerts with Beautifulsoup
* Removed some legacy code that was commented out

### Related issues

*
*

### Checklist

- [X] I consider the submitted work as finished
- [X] I tested the code for its functionality using different use cases
- [X] I added/update the relevant documentation (either on github or on notion)
- [X] Where necessary I refactored code to improve the overall quality

### Further comments

2024-12-24 13:50 UTC, flavienSindou commented
@pietrocapece Thank you for the feature addition and for cleaning up the code!

I noticed that the requirements file needs to be updated to resolve the merge conflict. Once that's done, I’ll be happy to approve your pull request.

2025-01-07 09:34 UTC, flavienSindou approved these changes

2025-02-21 10:55 UTC, flavienSindou requested changes
https://github.com/OpenCTI-Platform/connectors/pull/3047#issuecomment-2561151340

2025-02-21 11:01 UTC, flavienSindou approved these changes

2025-02-21 11:04 UTC, flavienSindou requested changes
Could you please sign this commit 
https://github.com/OpenCTI-Platform/connectors/pull/3047/commits/310cc90e9270ba7a5e81806c4ec73c8ed0caf3c8
the merge pipeline requests all commits are signed

https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

2025-02-24 10:50 UTC, flavienSindou commented
@pietrocapece 

The requirements file needs to be updated to resolve the merge conflict. 

Could you please sign this commit
https://github.com/OpenCTI-Platform/connectors/commit/310cc90e9270ba7a5e81806c4ec73c8ed0caf3c8
the merge pipeline requests all commits are signed

https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

Best regards.

2025-02-25 10:33 UTC, pietrocapece commented
So i keep having to update the requirements because you keep updating the app. Pleawe could you just merge my code so I dont have to keep doing this? I cannot sign the commits unfortunately, I have tried for months but the feature is not working from the linux subsystem I am working from. Happy to find another way to deliver this code foer you to upload but I am unable to sign the commits, and it is impossible to sign them retroactively.

2025-02-26 13:09 UTC, flavienSindou approved these changes

2025-02-26 13:11 UTC, flavienSindou requested changes
https://webdevstudios.com/2020/05/26/retroactively-sign-git-commits/

2025-02-27 07:08 UTC, helene-nguyen approved these changes

2025-02-27 07:09 UTC, merged