Change Recorded Future TLP values
OpenCTI-Platform/connectors pull request #3095
Opened 2024-12-09 18:34 UTC by Jonah-RF

### Proposed changes

* Changes the default TLP level of Recorded Future data to red
* Forces all finished intelligence reports to be TLP Red

### Checklist

- [ X] I consider the submitted work as finished
- [ X] I tested the code for its functionality using different use cases
- [ X] I added/update the relevant documentation (either on github or on notion)
- [ X] Where necessary I refactored code to improve the overall quality

### Further comments

2024-12-11 08:50 UTC, Jipegien requested changes
Fine with the code but:
- let the value "white" by default in the readme file
- details in the readme file that this default value is not taken into account for AnalystNotes and is forced to RED.

2024-12-16 11:15 UTC, Powlinett reviewed
Thanks for your PR @Jonah-RF 🙏

Here's my feedback:
✅ code looks good to me
✅ no errors during data ingestion
✅ seems to work as intended both locally and as docker image

💡As `TLP` env/config var is required and has a default value, it would be a better practice to reflect that in the code. So ideally, in [main.py](https://github.com/OpenCTI-Platform/connectors/blob/master/external-import/recorded-future/src/main.py#L53) , `self.tlp = get_config_variable(...)` should have `required=True` and `default="Red"` as keywords args. It will prevent errors like shown below if the env/config var is missing and/or display more meaningful error log.

![image](https://github.com/user-attachments/assets/e43f3162-0adf-4e6c-8fba-0c5740481d37)

If it's not already the case, please don't forget to sign all commits 😇

Many thanks!

2024-12-16 17:31 UTC, Powlinett commented on external-import/recorded-future/src/main.py
> +            required=True, ,
small typo (extra comma) ☹️

2024-12-17 09:24 UTC, Powlinett commented
Argh, the CI fails because the last commit is not formatted according to Black rules. Can you do it please? 😇 Thanks!
![image](https://github.com/user-attachments/assets/e68601ff-0da8-4072-a2a1-056758e93aca)

2024-12-17 09:25 UTC, Powlinett approved these changes

2024-12-20 15:15 UTC, Powlinett commented
Hi @Jonah-RF , I'm sorry to ping you again but we can't merge this PR until all the commits are signed 🫤 Could you sign them please? Thanks 🙏

2024-12-31 16:29 UTC, Jonah-RF commented
Happy Holidays @Powlinett! I rebased the branch to sign every commit - can you take a look when you have some time after the holidays?

2025-01-08 06:34 UTC, helene-nguyen commented
Close as changes have been added here: https://github.com/OpenCTI-Platform/connectors/pull/3213

2025-01-08 06:34 UTC, closed without merging