Brazilianian/abuse ssl/remove unused variable
OpenCTI-Platform/connectors pull request #3203
Opened 2024-12-27 10:05 UTC by Brazilianian

### Proposed changes

Just remove the variable to avoid confusion
Also filled doctrings to remove the warnigns

### Related issues

#3194 

### Checklist

- [X] I consider the submitted work as finished
- [X] I tested the code for its functionality using different use cases
- [X] I added/update the relevant documentation (either on github or on notion)
- [X] Where necessary I refactored code to improve the overall quality

### Further comments

2025-01-03 11:08 UTC, romain-filigran commented
Hello @Brazilianian : Thanks for your contribution.
In order to merge your PR, could you fix the problem with the lint verification ?
![Capture d'écran 2025-01-03 120458](https://github.com/user-attachments/assets/b87a40d6-6a64-4469-8208-721f58ac2048)

2025-01-03 13:02 UTC, Brazilianian commented
@romain-filigran Sure!

2025-01-03 17:29 UTC, romain-filigran commented
Checking the connector, it seems that the default CSV feed has been obsolete since the beginning of the year? 
@Brazilianian : Do you have the same observation?

2025-01-03 18:13 UTC, Brazilianian commented
@romain-filigran 

Yes, it looks like they closed both formats of ip feed:
[.txt](https://sslbl.abuse.ch/blacklist/sslipblacklist.txt) - Last updated: 2025-01-02 01:09:06 UTC   
[.csv](https://sslbl.abuse.ch/blacklist/sslipblacklist.csv) - Last updated: 2025-01-03 11:30:00 UTC 

I didnt find any articles or posts in social media about it

2025-01-06 10:53 UTC, helene-nguyen commented
@Brazilianian Thanks for your contribution! Could you sign your commits ? :)

2025-01-08 12:29 UTC, Brazilianian commented
@helene-nguyen 
Yes, sure
I'm sorry for the wait

2025-01-09 13:48 UTC, helene-nguyen requested changes
@Brazilianian All commits need to signed, could you do that please ? :)

2025-01-09 18:05 UTC, closed without merging