[import-file-pdf-observable] Rewrite of the entire connector
OpenCTI-Platform/connectors pull request #370
Opened 2021-05-26 19:10 UTC by nor3th

I decided to rewrite the entire connector to have a more modular design and to enable the addition of other fields by simple editing the config files instead of hardcoding everything.

Changes:

* Rewrite of the entire connector
* Support for the ingestion of txt files
* Renamed the connector, since "import-file-pdf-observable" doesn't reflect the connectors capabilities
* Added a basic README description
* Implementation of white lists for entities as well as observables

I wanted to push the major changes for now and the next steps will be the expansion of the whitelists and further regex patterns for different observables.

I forgot to pull the original repository from the opencti github repository and due to that some old commit messages are also shown in this PR. The relevant changes start at "Complete refactoring of the import pdf connector" (5690fc8)

2021-05-27 15:49 UTC, SamuelHassine approved these changes

2021-05-27 15:49 UTC, SamuelHassine requested changes
Hello,

Thanks for this amazing PR. Can you please solve the conflicts so we can merge it?

Thanks!

Kind regards,
Samuel

2021-05-27 19:15 UTC, nor3th commented
Conflict has been resolved

2021-05-28 07:21 UTC, SamuelHassine approved these changes

2021-05-28 07:21 UTC, merged

2021-05-28 07:22 UTC, SamuelHassine commented
Thanks a lot for the great work!