add LastInfoSec enrichment
OpenCTI-Platform/connectors pull request #495
Opened 2021-09-28 20:21 UTC by remydewa

This pull request add the LastInfoSec enricher to OpenCTI.

This connector enrich url and hash indicators by calling the LastInfoSec api.

2021-10-01 08:18 UTC, nor3th commented
Also please run `black .` to adapt the format of your code. 
Details: https://www.notion.so/Connector-Development-06b2690697404b5ebc6e3556a1385940#265b804393f64922aeff232315a6a171

2021-10-01 09:02 UTC, remydewa commented
Thanks nor3th! I did it. It looks good now :).

2021-10-01 12:25 UTC, nor3th requested changes
hey @remydewa 

Thank you very much for you effort.

Additionally to the comments, please make use of the PR template for your submission, as this helps us to get a better understanding of your work.

(This comment should have already been posted earlier, but I forgot to submit the review...)

Thanks

2021-10-01 12:25 UTC, nor3th commented on internal-enrichment/lastinfosec/src/requirements.txt
> +pycti==4.5.5
Please use the 5.0.2 pycti library for the connector (yes there's a version discrepancy between OpenCTI and the connectors (currently 5.0.1) and the pycti lib (currently 5.0.2).

2021-10-01 12:25 UTC, nor3th commented on internal-enrichment/lastinfosec/docker-compose.yml
> +    image: opencti/lastinfosec-enrichment:4.5.5
Please also change this to 5.0.1

2021-10-01 13:23 UTC, remydewa commented
hello @nor3th 
Thanks, I did the changes to the merge request content explaination.
Rémy

2021-10-03 08:33 UTC, nor3th commented
Great, but also please fix the mentioned version issues.

Thanks

2021-10-04 08:14 UTC, remydewa commented
Hello @nor3th 

It's done. I hope this time everything is ok?
Thanks,
Rémy

2021-10-04 18:00 UTC, nor3th commented
Hey @remydewa 

Yes, thank you very much for your effort! 

Regards,

2021-10-04 18:00 UTC, merged