data.json.gz not found
OpenCTI-Platform/connectors pull request #627
Opened 2022-03-09 00:01 UTC by izm1chael

### Proposed changes

* Set the static path when running the unzip command

### Related issues

* N/A

### Checklist

- [x ] I consider the submitted work as finished
- [x ] I tested the code for its functionality using different use cases
- [ x] I added/update the relevant documentation (either on github or on notion)
- [ x] Where necessary I refactored code to improve the overall quality

### Further comments

This should mitigate the failed to find data.json.gz issue I had experienced when trying to automate some connectors with various scripts and systemd

2022-03-09 20:10 UTC, nor3th requested changes

2022-03-09 20:10 UTC, nor3th commented on external-import/cve/src/cve.py
> +            with gzip.open(os.path.dirname(os.path.abspath(__file__)) + "data.json.gz", "rb") as f_in:
Hey @izm1chael 

Thanks for your PR, please fix the missing slash /

Regards

```suggestion
            with gzip.open(os.path.dirname(os.path.abspath(__file__)) + "/data.json.gz", "rb") as f_in:
```

2022-03-09 23:40 UTC, izm1chael commented
Update based on previous comments

2022-03-20 20:32 UTC, nor3th commented
Thanks for your PR, closing this for the referred commit.

2022-03-20 20:32 UTC, closed without merging